### PR TITLE
Add unlock state

### PR DESCRIPTION
**Pull request by patricktalmeida**
We all know that sometimes big terraform configuration files the terraform state, from time to time, tend to get locked. The idea of this PR is to favor who needs to unlock their terraform state.

Initially built for a manual trigger of a workflow with `workflow_dispatch` option as in README example.

### CODE REVIEW

**Comment by dflook** [comment]
Hi @patricktalmeida, thanks for working on this.

Is the `force` input necessary? I think it must always by "true", or it will hang waiting for confirmation.

**Comment by patricktalmeida** [comment]
> Hi @patricktalmeida, thanks for working on this.
> 
> Is the `force` input necessary? I think it must always by "true", or it will hang waiting for confirmation.

@dflook you are correct. Fixed it by totally removing the condition on `$INPUT_FORCE` as the option won't be necessary. 
Thanks for the review.

**Comment by patricktalmeida** [comment]
> > Hi @patricktalmeida, thanks for working on this.
> > Is the `force` input necessary? I think it must always by "true", or it will hang waiting for confirmation.
> 
> @dflook you are correct. Fixed it by totally removing the condition on `$INPUT_FORCE` as the option won't be necessary. Thanks for the review.

@dflook Any inputs in this? can it be merged?

**Comment by dflook** [comment]
Hello @patricktalmeida, I'm planning to add a test for this and merge it in for the next release

**Comment by dflook** [comment]
This was released in v1.32.0 🎉

**Comment by patricktalmeida** [comment]
> 

🎉🎉🎉

**Pull request merged**
