### PR TITLE
Update to support Terraform cloud with Terraform 1.6

### PR DESCRIPTION
**Pull request by dflook**

### CODE REVIEW

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #643](https://github.com/dflook/terraform-github-actions/actions/runs/7848447438)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #643](https://github.com/dflook/terraform-github-actions/actions/runs/7848447438)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #643](https://github.com/dflook/terraform-github-actions/actions/runs/7848447438)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #644](https://github.com/dflook/terraform-github-actions/actions/runs/7848800157)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #644](https://github.com/dflook/terraform-github-actions/actions/runs/7848800157)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #644](https://github.com/dflook/terraform-github-actions/actions/runs/7848800157)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #645](https://github.com/dflook/terraform-github-actions/actions/runs/7849269831)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #645](https://github.com/dflook/terraform-github-actions/actions/runs/7849269831)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #645](https://github.com/dflook/terraform-github-actions/actions/runs/7849269831)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #646](https://github.com/dflook/terraform-github-actions/actions/runs/7849418277)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #646](https://github.com/dflook/terraform-github-actions/actions/runs/7849418277)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #647](https://github.com/dflook/terraform-github-actions/actions/runs/7850208405)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #647](https://github.com/dflook/terraform-github-actions/actions/runs/7850208405)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #647](https://github.com/dflook/terraform-github-actions/actions/runs/7850208405)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #649](https://github.com/dflook/terraform-github-actions/actions/runs/7853925966)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #649](https://github.com/dflook/terraform-github-actions/actions/runs/7853925966)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #649](https://github.com/dflook/terraform-github-actions/actions/runs/7853925966)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #650](https://github.com/dflook/terraform-github-actions/actions/runs/7855017467)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #650](https://github.com/dflook/terraform-github-actions/actions/runs/7855017467)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #650](https://github.com/dflook/terraform-github-actions/actions/runs/7855017467)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #651](https://github.com/dflook/terraform-github-actions/actions/runs/7856578210)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #651](https://github.com/dflook/terraform-github-actions/actions/runs/7856578210)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #651](https://github.com/dflook/terraform-github-actions/actions/runs/7856578210)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #652](https://github.com/dflook/terraform-github-actions/actions/runs/7861365022)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #652](https://github.com/dflook/terraform-github-actions/actions/runs/7861365022)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #652](https://github.com/dflook/terraform-github-actions/actions/runs/7861365022)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #653](https://github.com/dflook/terraform-github-actions/actions/runs/7861716252)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #653](https://github.com/dflook/terraform-github-actions/actions/runs/7861716252)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #653](https://github.com/dflook/terraform-github-actions/actions/runs/7861716252)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #654](https://github.com/dflook/terraform-github-actions/actions/runs/7862053565)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_fine_grained_pat__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #655](https://github.com/dflook/terraform-github-actions/actions/runs/7862200240)

**Comment by dflook** [comment]
Terraform plan for __test-apply apply_user_token__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

Terraform will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #655](https://github.com/dflook/terraform-github-actions/actions/runs/7862200240)

**Comment by dflook** [comment]
OpenTofu plan for __test-apply apply_opentofu__
<details>
<summary>Plan: 1 to add, 0 to change, 0 to destroy. Changes to Outputs.</summary>

```diff
OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+   create

OpenTofu will perform the following actions:

  # random_string.my_string will be created
+   resource "random_string" "my_string" {
+       id          = (known after apply)
+       length      = 11
+       lower       = true
+       min_lower   = 0
+       min_numeric = 0
+       min_special = 0
+       min_upper   = 0
+       number      = true
+       numeric     = true
+       result      = (known after apply)
+       special     = true
+       upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+   output_string = "the_string"
```
</details>

:memo: Plan generated in [Test terraform-apply #655](https://github.com/dflook/terraform-github-actions/actions/runs/7862200240)

**Review by danielflooktech — COMMENTED** [review]
Triggering pull_request_review event...

**Pull request merged**
