### PR TITLE
allow override of docker image used to execute github action

### PR DESCRIPTION
**Pull request by crandles**
Allow users to extend the action by referencing any docker image, and have control over the entire container environment.

### CODE REVIEW

**Comment by dflook** [comment]
Hello @crandles. This brings the expectation that these actions would work on images that they have not been made for or tested with, which is not something I'm prepared to support.

With that in mind there is the [`TERRAFORM_PRE_RUN`](https://github.com/dflook/terraform-github-actions/tree/main/terraform-plan#environment-variables) environment variable which can be used to customise the container if needed, but is provided as an escape hatch only and there is no promise the container environment is consistent between releases.

What is it you need to change about the container environment?

**Comment by crandles** [comment]
1. I would like to inject some dependencies into the container before terraform runs.

Thanks for pointing out `TERRAFORM_PRE_RUN`, that solves some of my concerns, although it would require execution of commands at runtime, and waste resources from repetitive execution.

2. Apart from dependency injection, I have some reservations about the current Dockerfile base:

https://github.com/dflook/terraform-github-actions/blob/62d5bfdb5f722e68b0241a34cf46cfe8ee98fdbd/image/Dockerfile#L1

I have the following security-related concerns:
- I would prefer to always use a tagged image as a base
- I would prefer the ability to reference an image hosted in a docker image repository that I maintain
- I would prefer to rely on more community-owned images as a base instead of your own hosted image

I will likely fork this repository before running it in my organization, but would prefer to keep it unchanged from upstream as possible.

I would think any deviation of images would be up to users to support, and not your action, just as any complications from using the `TERRAFORM_PRE_RUN` command may introduce.

**Comment by dflook** [comment]
Regarding the docker images, the releases published to the marketplace reference a specific image digest. That image is also labelled with the digest of the base image it was built from and through labels can be traced back to the actions jobs and git commits that built them. The build logs are public and can be inspected to verify the built image matches the digest used in the action.

The action release versions are just tags though, which are not immutable. You can pin actions to git commits instead of the tag to ensure it can't be tampered with.

I think forking would be the right thing for you to do, as you can use your own hosted image.
It would probably be better not to merge this PR, as you can control the image used in your fork without worrying about it being overridden?

**Comment by crandles** [comment]
Sure, I can resort to forking + modifying the relevant references.

When it is an option, I prefer to mirror (and leave unchanged) open source artifacts vs maintaining my own fork that requires post-fork modifications, and that is what I was hoping to enable with this PR.

**Pull request closed without merging**
