### PR TITLE
Feat/multiple comments on prs

### PR DESCRIPTION
**Pull request by gusfcarvalho**
Fixes issue #296

### CODE REVIEW

**Comment by gusfcarvalho** [comment]
Hi @dflook ! Tried my best to figure out a logic here, but I might have been opinionated (allow `add_github_comment: always` option). If you have any suggestions to better add this logic, I'm happy to implement it! 😄

**Comment by dflook** [comment]
Hi @gusfcarvalho 👋  I think a new option for add_github_comment is good, but I'm not sure `always` is quite right.

When plans are being applied, the status field in the PR comments gets updated when the apply starts, and again when the apply finishes. This change would create multiple matching comments for the same plan, so we need to be sure we update the correct one.

When there are a lot of comments on a PR, finding the plan comment can use quite a lot of requests to the github api, so we currently use the first one we find and cache it as much as possible.

I think we should add a new `closed` header to comments when they should not be updated anymore. We can then ignore such comments when looking for one to update.

For this feature, it would be nice to update the status of any existing comment to say that the plan is outdated and also add the `closed` header. This can help make sure reviewers aren't looking at the wrong comment.

We can also add the `closed` header when adding the final status update for an apply. This would fulfil another feature request for people who iterate on changes by applying terraform while a PR is open, possibly multiple times, and would like to see each apply operation in a separate comment in the correct place on the timeline.

**Comment by gusfcarvalho** [comment]
> I think we should add a new closed header to comments when they should not be updated anymore. 

Will do!

> When there are a lot of comments on a PR, finding the plan comment can use quite a lot of requests to the github api, so we currently use the first one we find and cache it as much as possible.

this would be an update to the `find_comment` to include a fetch for the `closed` header, plus a logic on `_main_.py` to properly decide whether to find a comment (for the apply) and update the comment as closed,  or to create a new comment for a new plan (closing any previous plans), does that sound about right?

**Comment by dflook** [comment]
Yeah, that sounds good

**Comment by dflook** [comment]
Thanks for working on this @gusfcarvalho, it has been implemented in #308

**Pull request closed without merging**
